[project]
name = "m2i-projet-cdsd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "minio>=7.2.20",
    "pytest>=9.0.1",
    "python-dotenv>=1.2.1",
]
